const HOST='com.extnest.host';const $=id=>document.getElementById(id);let helperOnline=false,state={registry:[],installed:[],github:null,cloud:null,settings:null,paths:null},reposCache=[],toastTimer;
function toast(m){$('toast').textContent=m;$('toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),2600)}
function native(op,data={}){return new Promise((resolve,reject)=>chrome.runtime.sendNativeMessage(HOST,{op,...data},r=>{const e=chrome.runtime.lastError;if(e)reject(new Error(e.message));else resolve(r)}))}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setDot(id,s){const e=$(id);e.classList.remove('good','bad','warn');if(s)e.classList.add(s)}
async function installedDevelopmentExtensions(){const all=await chrome.management.getAll();return all.filter(x=>x.type==='extension'&&x.installType==='development'&&x.id!==chrome.runtime.id)}
function updateSidebar(){$('helperLabel').textContent=helperOnline?'online':'offline';setDot('helperDot',helperOnline?'good':'bad');$('gitLabel').textContent=state.github?.login||'não conectado';setDot('gitDot',state.github?'good':'warn');$('cloudLabel').textContent=state.cloud?.provider||'não configurada';setDot('cloudDot',state.cloud?'good':'warn');$('extCount').textContent=state.registry.length||''}
function setView(name){document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));$(`view-${name}`).classList.remove('hidden');document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===name));const t={extensions:['Minhas extensões','Código no GitHub. Instalação local no AppData. Configurações na sua nuvem.'],github:['GitHub','Selecione explicitamente quais repositórios fazem parte do ExtNest.'],cloud:['Nuvem','Backup leve do Vault e das configurações das extensões.'],settings:['Configurações','Comportamento do ExtNest neste computador.']}[name];$('viewTitle').textContent=t[0];$('viewSubtitle').textContent=t[1];$('headerActions').classList.toggle('hidden',name!=='extensions')}
async function refreshState(){try{const p=await native('ping');helperOnline=!!p?.ok;$('helperBanner').classList.toggle('hidden',helperOnline)}catch{helperOnline=false;$('helperBanner').classList.remove('hidden')}state.installed=await installedDevelopmentExtensions();if(helperOnline){const s=await native('state_get');if(s?.ok){state.registry=s.registry||[];state.github=s.github||null;state.cloud=s.cloud||null;state.settings=s.settings||null;state.paths=s.paths||null}}else state.registry=[];updateSidebar();await renderExtensions();renderDetected();renderGithub();renderPaths()}
async function statusFor(item){if(!helperOnline)return null;try{return await native('repo_status',{slug:item.slug})}catch{return null}}
async function bridgePing(id){try{return await chrome.runtime.sendMessage(id,{type:'extnest.ping',protocol:1})}catch{return null}}
function btn(label,cls,handler){const b=document.createElement('button');b.textContent=label;if(cls)b.className=cls;b.addEventListener('click',async()=>{try{await handler()}catch(e){toast(e.message)}});return b}
async function renderExtensions(){const w=$('extensionCards');w.innerHTML='';if(!state.registry.length){w.innerHTML='<div class="panel"><h2>Nenhuma extensão adicionada</h2><p>Conecte o GitHub e selecione os repositórios que devem aparecer aqui.</p></div>';return}for(const item of state.registry){const st=await statusFor(item),installed=state.installed.find(x=>x.id===(item.extension_id||st?.expected_extension_id)),localVersion=installed?.version||st?.local_version||'—',remoteVersion=st?.remote_version||'—',upd=!!(installed&&st?.update_available),local=!!st?.local_exists,bridge=installed?await bridgePing(installed.id):null;const card=document.createElement('article');card.className='card';card.innerHTML=`<div class="card-head"><div class="card-title"><div class="ext-icon"><img src="icons/icon32.png" alt=""></div><div><h3>${esc(item.name||item.slug)}</h3><span class="repo">${esc(item.repo)}</span></div></div><span class="badge ${upd?'warn':installed?'good':''}">${upd?'Atualização disponível':installed?'Instalada':local?'Preparada':'Na nuvem'}</span></div><div class="meta"><div class="meta-item"><span>Instalada</span><strong>${esc(localVersion)}</strong></div><div class="meta-item"><span>GitHub</span><strong>${esc(remoteVersion)}</strong></div><div class="meta-item"><span>Bridge de configurações</span><strong>${bridge?.ok?'Compatível':installed?'Não detectado':'—'}</strong></div><div class="meta-item"><span>Config na nuvem</span><strong>${st?.config_cloud?'Salva':st?.config_backup?'Somente local':'—'}</strong></div></div><div class="card-actions"></div>`;const a=card.querySelector('.card-actions');if(!local)a.append(btn('Instalar','main',()=>installRepo(item)));else if(!installed)a.append(btn('Carregar no Edge','main',()=>showInstall(st.local_path)));if(upd)a.append(btn('Atualizar','main',()=>updateRepo(item,installed)));if(local)a.append(btn('Abrir pasta','',()=>native('repo_open',{slug:item.slug})));if(installed&&bridge?.ok){a.append(btn('Backup cfg','',()=>backupConfig(installed.id)));if(st?.config_backup)a.append(btn('Restaurar cfg','',()=>restoreConfig(installed.id)))}a.append(btn('Verificar','',async()=>{await refreshState();toast('Verificação concluída.')}));
    if(installed&&bridge?.ok&&st?.config_backup&&state.settings?.ask_restore!==false&&item.ask_restore!==false){
      const prompt=document.createElement('div');prompt.className='restore-prompt';prompt.innerHTML='<strong>Configurações salvas encontradas</strong><span>Deseja usar o backup da nuvem neste computador?</span>';
      const pa=document.createElement('div');pa.className='prompt-actions';pa.append(btn('Restaurar','main',()=>restoreConfig(installed.id)));pa.append(btn('Começar limpa','',async()=>{await native('registry_set_restore_prompt',{slug:item.slug,value:false});await refreshState();toast('Não perguntarei novamente para esta extensão.')}));prompt.appendChild(pa);card.appendChild(prompt);
    }
    w.appendChild(card)}}
function renderDetected(){const ids=new Set(state.registry.map(x=>x.extension_id).filter(Boolean)),w=$('detectedList');w.innerHTML='';const u=state.installed.filter(x=>!ids.has(x.id));if(!u.length){w.innerHTML='<div class="hint">Nenhuma extensão de desenvolvimento não gerenciada detectada.</div>';return}for(const x of u){const r=document.createElement('div');r.className='detected';r.innerHTML=`<div class="grow"><strong>${esc(x.name)}</strong><span>${esc(x.id)} · v${esc(x.version)}</span></div><span class="badge">development</span>`;w.appendChild(r)}}
function renderGithub(){$('githubDisconnected').classList.toggle('hidden',!!state.github);$('githubConnected').classList.toggle('hidden',!state.github);if(state.github){$('githubUser').textContent=state.github.name||state.github.login;$('githubAccountDetail').textContent=`@${state.github.login}`;$('githubAvatar').textContent=(state.github.login||'?').slice(0,1).toUpperCase()}}
function renderPaths(){$('extensionsPath').textContent=state.paths?.extensions||'—';$('dataPath').textContent=state.paths?.data||'—';if(state.settings){$('autoCheck').checked=state.settings.auto_check!==false;$('checkInterval').value=String(state.settings.check_interval||360);$('autoConfigBackup').checked=state.settings.auto_config_backup!==false;$('askRestore').checked=state.settings.ask_restore!==false}}
async function connectGithub(){const token=$('githubToken').value.trim();if(!token)return toast('Cole um token do GitHub.');const r=await native('github_set_token',{token});if(!r?.ok)throw new Error(r?.error||'Falha ao conectar.');$('githubToken').value='';await refreshState();toast(`GitHub conectado como @${r.user.login}.`)}
async function loadRepos(){if(!state.github)return toast('Conecte o GitHub primeiro.');$('repoList').innerHTML='<div class="hint">Carregando…</div>';const r=await native('github_list_repos');if(!r?.ok)throw new Error(r?.error||'Falha ao listar.');reposCache=r.repos||[];renderRepoList()}
function renderRepoList(){const q=$('repoSearch').value.trim().toLowerCase(),managed=new Set(state.registry.map(x=>x.repo.toLowerCase())),w=$('repoList');w.innerHTML='';for(const repo of reposCache.filter(x=>!q||x.full_name.toLowerCase().includes(q))){const r=document.createElement('label');r.className='repo-row'+(repo.private?' private':'');r.innerHTML=`<input type="checkbox" data-repo="${esc(repo.full_name)}" ${managed.has(repo.full_name.toLowerCase())?'disabled':''}><div class="grow"><strong>${esc(repo.full_name)}</strong><span>${esc(repo.description||'Sem descrição')} · ${esc(repo.default_branch||'main')}</span></div>${managed.has(repo.full_name.toLowerCase())?'<span class="badge good">Adicionado</span>':''}`;w.appendChild(r)}}
async function addSelectedRepos(){const sel=[...document.querySelectorAll('#repoList input:checked')].map(x=>x.dataset.repo);if(!sel.length)return toast('Selecione ao menos um repositório.');const map=new Map(reposCache.map(x=>[x.full_name,x]));for(const full of sel){const repo=map.get(full),r=await native('repo_register',{repo:full,branch:repo?.default_branch||'main'});if(!r?.ok)toast(`${full}: ${r?.error||'erro'}`)}await refreshState();renderRepoList();setView('extensions');toast('Repositórios adicionados.')}
async function installRepo(item){const r=await native('repo_install',{slug:item.slug});if(!r?.ok)throw new Error(r?.error||'Falha ao baixar.');await refreshState();showInstall(r.path)}
function showInstall(path){$('installPath').textContent=path||'';$('installModal').classList.remove('hidden');$('modalBackdrop').classList.remove('hidden')}
async function updateRepo(item,installed){if(!confirm(`Atualizar ${item.name||item.slug} a partir do GitHub?`))return;if(installed){try{await backupConfig(installed.id,true)}catch{}}const r=await native('repo_update',{slug:item.slug});if(!r?.ok)throw new Error(r?.error||'Falha ao atualizar.');if(installed){const bridge=await bridgePing(installed.id);if(bridge?.ok){try{await chrome.runtime.sendMessage(installed.id,{type:'extnest.reload',protocol:1})}catch{}}else toast('Arquivos atualizados. Recarregue em edge://extensions.')}await refreshState()}
async function backupConfig(id,quiet=false){const r=await chrome.runtime.sendMessage({type:'extnest.ui.backup-config',extensionId:id});if(!r?.ok)throw new Error(r?.error||'Falha no backup.');if(!quiet)toast(r.cloud?'Configurações salvas na nuvem.':'Backup salvo localmente. Configure uma nuvem para sincronizar.');await refreshState()}
async function restoreConfig(id){if(!confirm('Substituir as configurações atuais pelas salvas na nuvem?'))return;const r=await chrome.runtime.sendMessage({type:'extnest.ui.restore-config',extensionId:id});if(!r?.ok)throw new Error(r?.error||'Falha ao restaurar.');toast('Configurações restauradas.')}
async function detectCloud(){const r=await native('cloud_detect');if(!r?.ok)throw new Error(r?.error||'Falha ao detectar.');const w=$('cloudCandidates');w.innerHTML='';if(!r.candidates?.length){w.innerHTML='<div class="hint">Nenhuma pasta sincronizada detectada automaticamente.</div>';return}for(const c of r.candidates){const row=document.createElement('div');row.className='cloud-row';row.innerHTML=`<div class="grow"><strong>${esc(c.provider)}</strong><span>${esc(c.path)}</span></div>`;row.appendChild(btn('Usar','main',async()=>{const s=await native('cloud_set',{provider:c.provider,path:c.path});if(!s?.ok)throw new Error(s?.error||'Falha.');await refreshState();toast(`${c.provider} definido como destino.`)}));w.appendChild(row)}}
async function saveSettings(){const s={auto_check:$('autoCheck').checked,check_interval:Number($('checkInterval').value),auto_config_backup:$('autoConfigBackup').checked,ask_restore:$('askRestore').checked};if(helperOnline)await native('settings_set',{settings:s});if(s.auto_check)await chrome.alarms.create('extnest-check-updates',{periodInMinutes:s.check_interval});else await chrome.alarms.clear('extnest-check-updates')}
document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$('refreshBtn').addEventListener('click',()=>refreshState().then(()=>toast('Atualizado.')));$('addRepoBtn').addEventListener('click',()=>setView('github'));$('connectGithubBtn').addEventListener('click',()=>connectGithub().catch(e=>toast(e.message)));$('disconnectGithubBtn').addEventListener('click',async()=>{await native('github_clear_token');await refreshState()});$('loadReposBtn').addEventListener('click',()=>loadRepos().catch(e=>toast(e.message)));$('repoSearch').addEventListener('input',renderRepoList);$('addSelectedReposBtn').addEventListener('click',()=>addSelectedRepos().catch(e=>toast(e.message)));$('detectCloudBtn').addEventListener('click',()=>detectCloud().catch(e=>toast(e.message)));$('copyInstallPath').addEventListener('click',async()=>{await navigator.clipboard.writeText($('installPath').textContent);toast('Caminho copiado.')});$('openExtensionsPage').addEventListener('click',()=>chrome.tabs.create({url:'edge://extensions/'}));document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>{$(b.dataset.close).classList.add('hidden');$('modalBackdrop').classList.add('hidden')}));for(const id of ['autoCheck','checkInterval','autoConfigBackup','askRestore'])$(id).addEventListener('change',()=>saveSettings().catch(()=>{}));refreshState().catch(e=>toast(e.message));
